### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by PratishShrivastava** [Code-Outside/hacktober-fest-2022#30]
please add this link at last to readme as

```
## Hall of Fame
[![Contributors](https://contrib.rocks/image?repo=Code-Outside/hacktober-fest-2022)](https://github.com/Code-Outside/hacktober-fest-2022/graphs/contributors)
```

**Comment by sujal-goswami** [comment]
hey @PratishShrivastava I want to work on this can you assign this to me

**Comment by sujal-goswami** [comment]
> hey @PratishShrivastava I want to work on this can you assign this to me

I know How MarkDown works

**Comment by PratishShrivastava** [comment]
go ahead @sujal-goswami

**Comment by sujal-goswami** [comment]
did you want this to show above the END heading or below

**Comment by PratishShrivastava** [comment]
above end.

**Comment by sujal-goswami** [comment]
is this looks fine
<img width="851" alt="image" src="https://user-images.githubusercontent.com/107000806/195775777-5cb2ca58-4fc1-45d1-89ff-ca9bcac0edd1.png">
