### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by saubhagya-gupta** [Code-Outside/hacktober-fest-2022#5]
I can create "Hello World" prgram in several languages like C, CPP, JAVA, JS, PY, etc..etc.. inside sepeate folders of the language.
For example, inside C folder -> HelloWorld.c
Inside Java folder -> HelloWorld.java
and so on.

**Comment by PratishShrivastava** [comment]
YES @saubhagya-gupta

**Comment by saubhagya-gupta** [comment]
Hi @PratishShrivastava, Added this PR : https://github.com/Code-Outside/hacktober-fest-2022/pull/6, Please review.

**Comment by PratishShrivastava** [comment]
You just need to add 1 languages Hello world program, please change it. @saubhagya-gupta
